config/routes.rb
Rails.application.routes.draw do
  
  
  # get 'sessions/new'
  # get 'users/index'
  # # get 'reviews/index'
  # get 'computers/index'
  
 
  get 'search', to: "computers#search"
  
  get 'signup' => 'users#new'
  resources :users
  resources :sessions
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'authentications#create'
  
  # get computers/6/reviews/3
  resources :computers do 
    resources :reviews
  end
  
    
  # get 'home/index'
  root to: 'home#index'
  get "about" => 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/computer.rb
class Computer < ApplicationRecord
    has_many :reviews
    belongs_to :user
    has_one_attached :image
    
    # a computer must have a name before being saved  
    validates :model, presence: true 
    
    
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  
  # call load_computer before every pubice method get called, expect...
  before_action :load_computer, except: [:index, :new, :create, :search]
  before_action :authenticate, except: [:index, :show]
  # before_action :right_person(@computer), except: [:index, :show]
  # stating which HTTP verb and what URL will call that method.
  
  
  # GET - /computers
  def index
    @computers = Computer.all
    # only display current users' computers, this is not we want in this app, every one should be able to see all computers 
    # @computers = current_user.computers
    
  end
  
  # GET - /computers/new
  def new
    @computer = Computer.new 
  end
  
  # POST - /computers
  def create
    @computer = Computer.new computer_params
    @computer.user = current_user
    if @computer.save
      redirect_to computers_path, notice: "Computer Created."
    else
      render :new # update the view 
    end
  end
  
  # GET - /computers/:id/edit
  def edit
    if !right_person(@computer)
       redirect_to root_path, alert: "Invalid Request"
    end
    # @computer = Computer.find params[:id]
  end
  
  # PATCH/PUT - /computers/:id
  def update
    # @computer = Computer.find params[:id]
    if @computer.update computer_params
      redirect_to @computer, notice: "Computer Updated."
    else
      render :edit
    end
  end
  
  # DELETE - /computers/:id
  def destroy
    # @computer = Computer.find params[:id]
    if !right_person(@computer)
       redirect_to root_path, alert: "Invalid Request"
    else
      @computer.destroy
      redirect_to @computer, alert: "Computer Deleted."
    end
  end
  
  # GET - /computers/:id
  def show
    # @computer = Computer.find params[:id]
    @review = Review.new
    
    
  end
  
  def search # use SQL to search, ? is the placeholder, it means the parameter
    @computers = Computer.where("model LIKE ?", "%" + params[:q] + "%")
  end 
  
  private 
  
  def load_computer
    @computer = Computer.find params[:id]
  end
  
  def computer_params
    params.require(:computer).permit(:model,:price,:cpu,:os,:disk,:ram,:screen,:image)
  end
  
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_computer.html.erb
<div id='computer_<%= computer.id %>' class='computer'>
    
    <div class="card" style="width: 18rem;">
      <!--<img src="https://cdn.pixabay.com/photo/2016/11/29/08/41/apple-1868496_960_720.jpg" class="card-img-top" alt="...">-->

      <div class="card-img-top"> 
      <% if @computer.image.attached? %>
        <%= image_tag @computer.image, style: "width: 100%; display: block" %>
        <!-- style: "width: 200px; display: block"-->
      <% else %>
        <p>...</p>
        <p>no image provided</p>
        <p>...</p>
      <% end  %>
      </div>

      <div class="card-body">
        <h5 class="card-title"><p><strong>Model:</strong>  <%= link_to_unless_current computer.model, computer %> </p></h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><p><strong>Price:</strong> <%= computer.price %> </p></li>
        <li class="list-group-item"><p><strong>CPU:</strong> <%= computer.cpu %> </p></li>
        <li class="list-group-item"><p><strong>OS:</strong> <%= computer.os %> </p></li>
        <li class="list-group-item"><p><strong>Disk:</strong> <%= computer.disk %> </p></li>
        <li class="list-group-item"><p><strong>RAM:</strong> <%= computer.ram %> </p></li>
        <li class="list-group-item"><p><strong>Screen:</strong> <%= computer.screen %> </p></li>
      </ul>
      
    </div>

</div>

app/views/computers/_form.html.erb
<%= bootstrap_form_with(model: @computer, local: true, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>

  <%= f.alert_message "Please fix the errors below.", error_summary: false %>
 
  <%= f.text_field :model %>
  <%= f.text_field :price %>
  <%= f.text_field :cpu %>
  <%= f.text_field :os %>
  <%= f.text_field :disk %>
  <%= f.text_field :ram %>
  <%= f.text_field :screen %>
  
  <%= f.file_field :image %>
  
  <!--<p><%=@computer.image.attached?%></p>-->
  
  <!--<% if @computer.image.attached? %>-->
  <!--  <%= image_tag @computer.image %>-->
  <!--<% end  %>-->
  <!--<br>-->
  

  <%= f.form_group do %>
    <%= f.primary @computer.persisted? ? "Update Computer" : "Create Computer"%>
  <% end %>
<% end %>

app/views/computers/edit.html.erb
<% title "Edit Computer" %>

<%= render "form" %>

<%= link_to "Cancel", computers_path, class: "btn btn-secondary" %>  

app/views/computers/index.html.erb
<% title "Computers"%>


<ul class="list-group list-group-flush">
    <% @computers.each do |computer|%>
        <li class="list-group-item">
            <div id='computer_<%= computer.id %>' class='computer'>
                <p><%= link_to_unless_current computer.model, computer %> </p>
                <p><%= computer.price %> </p>
            </div>
        </li>
    <% end %>
</ul>


<div class="newcomputerbutton">
    <%= link_to "New Computer", new_computer_path, class: "btn btn-primary" %>
</div>

app/views/computers/new.html.erb
<% title "New Computer" %>





<%= render 'form' %>

<%= link_to "Cancel", computers_path, class: "btn btn-secondary" %>  

app/views/computers/search.erb
<h1>Search Results</h1>

<ul class="list-group list-group-flush">
    <% @computers.each do |computer|%>
        <li class="list-group-item">
            <div id='computer_<%= computer.id %>' class='computer'>
                <p><%= link_to_unless_current computer.model, computer %> </p>
                <p><%= computer.price %> </p>
            </div>
        </li>
    <% end %>
</ul>

app/views/computers/show.html.erb
<% title "Computer" %>

<%= render @computer %>

<!--<%= link_to "Reviews", computer_reviews_path(@computer) %> |-->


<% if right_person(@computer) %>
    <%= link_to "Edit", edit_computer_path(@computer) %> | 
    <%= link_to "Delete", @computer, method: :delete, data: {confirm: "Are you sure?" } %> | 
<% end %>

<%= link_to "All Computers", computers_path %>  


<p></p>

<h2>Reviews</h2>


<!--<%= render @computer.reviews %>-->


<ul class="list-group list-group-flush">
    <% @computer.reviews.each do |review|%>
        <li class="list-group-item">
            <div id='review_<%= review.id %>' class='review'>
                <p>Content: <%= link_to_unless_current review.content, computer_review_path(@computer, review) %> </p>
                <p>Score: <%= review.score %> </p>
                <%= link_to "Edit", edit_computer_review_path(@computer, review) %> | 
                <%= link_to "Delete", computer_review_path(@computer, review), method: :delete, data: {confirm: "Are you sure?" } %>
            </div>
        </li>
        
        
    <% end %>
</ul>



<br>

<%= render 'reviews/form' %>

<br> 

<!--<%= link_to "New Review", new_computer_review_path(@computer), class: "btn btn-primary"%>-->