config/routes.rb
Rails.application.routes.draw do
  
  
  # get 'sessions/new'
  # get 'users/index'
  # # get 'reviews/index'
  # get 'computers/index'
  
 
  get 'search', to: "computers#search"
  
  get 'signup' => 'users#new'
  resources :users
  resources :sessions
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'authentications#create'
  
  # get computers/6/reviews/3
  resources :computers do 
    resources :reviews
  end
  
    
  # get 'home/index'
  root to: 'home#index'
  get "about" => 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="BYUH CS 401 Fall 2020">
    <meta name="author" content="Litian Zhang">
    
    <title>FinalApp <%= " | " + yield(:title) unless yield(:title).blank? %> </title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <nav class="navbar navbar-expand-md navbar-light bg-primary fixed-top">
      <a class="navbar-brand" href="/">
        <img src="https://cdn.pixabay.com/photo/2015/01/21/14/14/apple-606761_960_720.jpg" alt="Logo" style="width:40px;">
    
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <%= nav_link "Home", root_path %>
          <!--<%= nav_link "About", about_path%>-->
          <%= nav_link "Computers", computers_path %>
        </ul>
        
        <ul class="navbar-nav pull-right">
          <form class="form-inline my-2 my-lg-0" action="/search">
            <!--name="q" means we are passing q as parameter, value of q is what we enterred-->
            <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search"> 
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <% if current_user %>
            <%= nav_link current_user.username, current_user %>
            <%= nav_link "Logout", logout_path %>
          <% else %>
            <%= nav_link "Sign Up", signup_path %>
            <%= nav_link "Login", login_path  %>
          <% end %>
        </ul>
      </div>
    </nav>
    
      


<main role="main" class="container">

    <!--<h1>Good Good Study Day Day Up</h1>-->
    
    <% if @show_title %>
    <div id='title' class='row'>
      <div class='col'>
        <h1><%= yield(:title) %></h1>
      </div>
    </div>
    <% end %>

    <div id='flash-messages' class='row'>
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= name =='notice' ? 'primary' : 'danger' %> alert-dismissable col' role='alert'>
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    
    </div>

    <%= yield %>

</main><!-- /.container -->


    
  </body>
  
  <br>
     <hr class="rgba-white-light" style="margin: 0 15%;">

<!-- Footer -->
<footer class="page-footer font-small blue">


<!-- Grid row-->
    <div class="row text-center d-flex justify-content-center pt-5 mb-3">

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="https://www.churchofjesuschrist.org/?lang=eng">Belief</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="https://www.byuh.edu/">School</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="https://about.byuh.edu/directory/christopher-slade">Professor</a>
        </h6>
      </div>
      <!-- Grid column -->
      
      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="https://litianzhang.com/">Author</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="https://www.linkedin.com/in/litianzhang/">LinkedIn</a>
        </h6>
      </div>
      <!-- Grid column -->
      
      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="https://github.com/flybaflyba">GitHub</a>
        </h6>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
 

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> litianzhang.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
  
</html>